import {
  HeartOutlined,
  LeftOutlined,
  RightOutlined,
  SearchOutlined,
  ShoppingCartOutlined,
} from "@ant-design/icons";
import { Button, Card, Carousel, Input, List, message } from "antd";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import groceries from "./assets/groceries.png";
import hardware from "./assets/hardware.png";
import pharmacy from "./assets/pharmacy.png";
import appliances from "./assets/appliances.png";
import departmentStore from "./assets/departmentStore.png";
import more from "./assets/more.png";
import Link from "next/link";
import banner from "./assets/img-1.png";
import mask from "./assets/mask.png";

export default function Home() {
  const list = [
    { label: "Groceries", img: groceries, link: "/" },
    { label: "Hardware", img: hardware, link: "/" },
    { label: "Pharmacy", img: pharmacy, link: "/" },
    { label: "Appliances", img: appliances, link: "/" },
    { label: "Department Store", img: departmentStore, link: "/" },
    { label: "More", img: more, link: "/" },
  ];
  const list1 = [
    { label: "Groceries", img: groceries, link: "/" },
    { label: "Hardware", img: hardware, link: "/" },
    { label: "Pharmacy", img: pharmacy, link: "/" },
    { label: "Appliances", img: appliances, link: "/" },
    { label: "Department Store", img: departmentStore, link: "/" },
    { label: "More", img: more, link: "/" },
    { label: "Groceries", img: groceries, link: "/" },
    { label: "Hardware", img: hardware, link: "/" },
  ];

  const list2 = [
    { title: 'GROCERIES', cards: [
      {name: 'Robinsons Supermarket', desc: 'Groceries', img: '' },
      {name: 'Shopwise', desc: 'Fresh Goods, Groceries, Toys, Clothes', img: '' },
      {name: 'The Marketplace', desc: 'Luxury Groceries, Imported Goods', img: '' },
      {name: 'No Brand', desc: 'Korean Fronchise', img: '' },
      {name: 'Robinsons Easymart', desc: 'Specicilty', img: '' },
    ]},
    { title: 'HARDWARE', cards: [
      {name: 'Handyman', desc: 'DIY products, Appliances, Pets ', img: '' },
      {name: 'True Value', desc: 'Harchware, Household Supplies', img: '' },
    ]},
    { title: 'OTHER BRANDS', cards: [
      {name: 'Southstar Drug', desc: 'Pharmacy', img: '' },
      {name: 'Robinsons Appliances', desc: 'Appliances, Home Improvements', img: '' },
      {name: 'Toys R Us', desc: 'Toys and Action Figures', img: '' },
      {name: 'Shiseido', desc: 'Specialty', img: '' },
      {name: 'Pets Lovers Center', desc: 'Specialty', img: '' },
      {name: 'Daiso', desc: 'Convenience Store', img: '' },
      {name: 'Mini Stop', desc: 'Quick Bites', img: '' },
    ]},
  ]

  const bannerList = [banner, banner, banner, banner, banner];

  return (
    <div className={styles.container}>
      <Head>
        <title>GoCart Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">What would you like to explore today?</h1>
        <div className="search-div">
          <Input
            placeholder="What are you looking for?"
            suffix={<SearchOutlined />}
          />
        </div>
        <div className="categories">
          <List
            grid={{ gutter: 16, xs: 1, sm: 3, md: 3, lg: 6, xl: 6, xxl: 6 }}
            dataSource={list}
            renderItem={(item, index) => (
              <List.Item key={index}>
                <Link href={item.link}>
                  <a>
                    <Image
                      src={item.img}
                      alt={item.label}
                      width={100}
                      height={100}
                    />
                    <span className="label">{item.label}</span>
                  </a>
                </Link>
              </List.Item>
            )}
          />
        </div>
        <div className="carousel">
          <Carousel
            autoplay
            arrows={true}
            prevArrow={<LeftOutlined />}
            nextArrow={<RightOutlined />}
          >
            {bannerList.map((item, index) => (
              <Image src={item} width={1180} height={491} key={index} />
            ))}
          </Carousel>
          {/* <span className="left-btn" onClick={() => next()}><LeftOutlined /></span>
          <span className="right-btn"><RightOutlined /></span> */}
        </div>
        <div className="promotions">
          <h1>Promotions</h1>
          <List
            grid={{ gutter: 16, xs: 2, sm: 2, md: 4, lg: 8, xl: 8, xxl: 8 }}
            dataSource={list1}
            renderItem={(item, index) => (
              <List.Item key={index}>
                <Link href={item.link}>
                  <a>
                    <Image
                      src={item.img}
                      alt={item.label}
                      width={100}
                      height={100}
                    />
                    <span className="label">{item.label}</span>
                  </a>
                </Link>
              </List.Item>
            )}
          />
        </div>
        <div className="featured-products">
          <div className="title">
            <h1>Featured Products</h1>
            <span>View All</span>
          </div>
          <div className="card-list">
            <List
              grid={{ gutter: 16, xs: 1, sm: 2, md: 3, lg: 6, xl: 6, xxl: 6 }}
              dataSource={list}
              renderItem={(item, index) => (
                <List.Item key={index}>
                  <Card
                    cover={
                      <img
                        alt="example"
                        src={
                          item.src ||
                          "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png"
                        }
                      />
                    }
                  >
                    <div className="name">
                      {item.name || "Robinsons Supermarket"}
                    </div>
                    <div className="desc">
                      {item.desc ||
                        "Anta Bubble Shoes 2 - Running Shoes (Ivory White) - 6"}
                    </div>
                    <div className="tags">
                      {item.tags?.map((tag) => (
                        <span style={{ background: tag.bgColor }}>
                          {tag.label}
                        </span>
                      ))}
                      <span>3 Variations</span>
                      <span>Save ₱115.50 </span>
                    </div>
                    <div className="footer-div">
                      <div>
                        <span className="cur-price">
                          {item.curPrice || "₱115.50"}
                        </span>
                        <span className="old-price">
                          {item.oldPrice || "₱115.50"}
                        </span>
                      </div>
                      <div>
                        <Button
                          icon={<HeartOutlined />}
                          onClick={() => {
                            message.info("被点击了收藏");
                          }}
                        />
                        <Button
                          icon={<ShoppingCartOutlined />}
                          onClick={() => {
                            message.info("被点击了购物车");
                          }}
                        />
                      </div>
                    </div>
                  </Card>
                </List.Item>
              )}
            />
          </div>
        </div>
        <div className="our-brands">
          <h1 className="title">Our Brands</h1>
         {list2.map((item) => {
            return (
              <div className="brand-list">
                <h2>{item.title}</h2>
                <List
                  grid={{ gutter: 16, xs: 1, sm: 2, md: 3, lg: 5, xl: 5, xxl: 5 }}
                  dataSource={item.cards}
                  renderItem={(card, index) => (
                    <List.Item key={index}>
                      <Card cover={<Image alt="example" src={mask} />}>
                        <div className="title">{card.name}</div>
                        <div className="desc">{card.desc}</div>
                      </Card>
                    </List.Item>
                  )}
                />
              </div>
            );
         })}
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
